

import type { Artist, Booking, Customer, ServicePackage, Promotion, Review } from '@/types';

export const artists: Artist[] = [
  {
    id: '1',
    name: 'Aisha Mehmood',
    email: 'aisha.mehmood@example.com',
    phone: '9876543210',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=1',
    workImages: [
      'https://picsum.photos/600/400?random=11',
      'https://picsum.photos/600/400?random=12',
      'https://picsum.photos/600/400?random=13',
    ],
    services: ['mehndi'],
    location: 'Mumbai, India',
    charge: 2500,
    charges: { mehndi: 2500 },
    rating: 4.9,
    styleTags: ['bridal', 'arabic', 'intricate'],
    unavailableDates: [],
    reviews: [
        { id: 'ar_1_1', customerName: 'Priya Patel', rating: 5, comment: 'Amazing detailed work!' }
    ],
    serviceOfferings: [
        { masterPackageId: 'pkg_bridal_mehndi', categoryName: 'Normal', artistPrice: 3500, isEnabled: true },
        { masterPackageId: 'pkg_bridal_mehndi', categoryName: 'Premium', artistPrice: 6000, isEnabled: true },
    ]
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    phone: '9876543211',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=2',
    workImages: [
      'https://picsum.photos/600/400?random=21',
      'https://picsum.photos/600/400?random=22',
      'https://picsum.photos/600/400?random=23',
    ],
    services: ['makeup'],
    location: 'Delhi, India',
    charge: 5000,
    charges: { makeup: 5000 },
    rating: 4.8,
    styleTags: ['glam', 'natural', 'wedding'],
    unavailableDates: [],
    serviceOfferings: [
        { masterPackageId: 'pkg_party_makeup', categoryName: 'Normal', artistPrice: 2500, isEnabled: true },
        { masterPackageId: 'pkg_party_makeup', categoryName: 'Premium', artistPrice: 4500, isEnabled: true },
        { masterPackageId: 'pkg_party_makeup', categoryName: 'ULTRA PREMIUM', artistPrice: 7500, isEnabled: true },
    ]
  },
  {
    id: '3',
    name: 'Rani Kaur',
    email: 'rani.kaur@example.com',
    phone: '9876543212',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=3',
    workImages: [
      'https://picsum.photos/600/400?random=31',
      'https://picsum.photos/600/400?random=32',
      'https://picsum.photos/600/400?random=33',
    ],
    services: ['mehndi', 'makeup'],
    location: 'Bangalore, India',
    charge: 7000,
    charges: { mehndi: 3000, makeup: 4000 },
    rating: 5.0,
    styleTags: ['luxury', 'traditional', 'modern'],
    unavailableDates: [],
  },
  {
    id: '4',
    name: 'Sunita Patel',
    email: 'sunita.patel@example.com',
    phone: '9876543213',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=4',
    workImages: [
      'https://picsum.photos/600/400?random=41',
      'https://picsum.photos/600/400?random=42',
      'https://picsum.photos/600/400?random=43',
    ],
    services: ['mehndi'],
    location: 'Ahmedabad, India',
    charge: 1800,
    charges: { mehndi: 1800 },
    rating: 4.7,
    styleTags: ['minimalist', 'floral', 'indian'],
    unavailableDates: [],
  },
  {
    id: '5',
    name: 'Fatima Khan',
    email: 'fatima.khan@example.com',
    phone: '9876543214',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=5',
    workImages: [
      'https://picsum.photos/600/400?random=51',
      'https://picsum.photos/600/400?random=52',
      'https://picsum.photos/600/400?random=53',
    ],
    services: ['makeup'],
    location: 'Hyderabad, India',
    charge: 4500,
    charges: { makeup: 4500 },
    rating: 4.9,
    styleTags: ['dewy', 'bold', 'party'],
    unavailableDates: [],
  },
  {
    id: '6',
    name: 'Geeta Singh',
    email: 'geeta.singh@example.com',
    phone: '9876543215',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=6',
    workImages: [
      'https://picsum.photos/600/400?random=61',
      'https://picsum.photos/600/400?random=62',
      'https://picsum.photos/600/400?random=63',
    ],
    services: ['mehndi', 'makeup'],
    location: 'Pune, India',
    charge: 6500,
    charges: { mehndi: 3000, makeup: 3500 },
    rating: 4.8,
    styleTags: ['airbrush', 'arabic', 'fusion'],
    unavailableDates: [],
  },
    {
    id: '7',
    name: 'Zara Begum',
    email: 'zara.begum@example.com',
    phone: '9876543216',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=7',
    workImages: [
      'https://picsum.photos/600/400?random=71',
      'https://picsum.photos/600/400?random=72',
      'https://picsum.photos/600/400?random=73',
    ],
    services: ['mehndi'],
    location: 'Kolkata, India',
    charge: 3000,
    charges: { mehndi: 3000 },
    rating: 4.9,
    styleTags: ['traditional', 'peacock', 'detailed'],
    unavailableDates: [],
  },
  {
    id: '8',
    name: 'Simran Reddy',
    email: 'simran.reddy@example.com',
    phone: '9876543217',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=8',
    workImages: [
      'https://picsum.photos/600/400?random=81',
      'https://picsum.photos/600/400?random=82',
      'https://picsum.photos/600/400?random=83',
    ],
    services: ['makeup'],
    location: 'Chennai, India',
    charge: 5500,
    charges: { makeup: 5500 },
    rating: 4.7,
    styleTags: ['south indian', 'bridal', 'temple'],
    unavailableDates: [],
  },
  {
    id: '9',
    name: 'Rohan Sharma',
    email: 'rohan.sharma@example.com',
    phone: '9876543218',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=9',
    workImages: [
      'https://picsum.photos/600/400?random=91',
      'https://picsum.photos/600/400?random=92',
      'https://picsum.photos/600/400?random=93',
    ],
    services: ['photography'],
    location: 'Jaipur, India',
    charge: 12000,
    charges: { photography: 12000 },
    rating: 4.9,
    styleTags: ['candid', 'wedding', 'pre-wedding'],
    unavailableDates: [],
  },
  {
    id: '10',
    name: 'Anjali Gupta',
    email: 'anjali.gupta@example.com',
    phone: '9876543219',
    password: 'Password@123',
    profilePicture: 'https://picsum.photos/200/200?random=10',
    workImages: [
      'https://picsum.photos/600/400?random=101',
      'https://picsum.photos/600/400?random=102',
    ],
    services: ['photography', 'makeup'],
    location: 'Goa, India',
    charge: 15000,
    charges: { photography: 10000, makeup: 5000 },
    rating: 4.8,
    styleTags: ['destination wedding', 'candid', 'natural'],
    unavailableDates: [],
  },
];

export const initialCustomers: Customer[] = [
    { id: 'cust_101', name: 'Priya Patel', email: 'priya.p@email.com', phone: '9123456780' },
    { id: 'cust_102', name: 'Amit Singh', email: 'amit.singh@email.com', phone: '9098765432' },
    { id: 'cust_103', name: 'Sunita Rao', email: 'sunita.r@email.com', phone: '9988776655' }
];

export const allBookings: Booking[] = [
    { id: 'book_01', customerId: 'cust_101', artistIds: ['1'], customerName: 'Priya Patel', customerContact: '9876543210', eventType: 'Wedding', serviceAddress: '123, Rose Villa, Bandra West, Mumbai', serviceDates: [new Date('2024-07-20')], date: new Date('2024-07-20'), service: 'Bridal Mehndi', amount: 5000, status: 'Completed', paidOut: true, eventDate: new Date('2024-07-22'), state: 'Maharashtra', district: 'Mumbai', location: 'Bandra West' },
    { id: 'book_02', customerId: 'cust_102', artistIds: ['2'], customerName: 'Anjali Sharma', customerContact: '9876543211', eventType: 'Party', serviceAddress: '456, Sunshine Apts, Saket, New Delhi', serviceDates: [new Date('2024-07-25')], date: new Date('2024-07-25'), service: 'Party Makeup', amount: 3000, status: 'Completed', paidOut: false, eventDate: new Date('2024-07-25'), state: 'Delhi', district: 'South Delhi', location: 'Saket' },
    { id: 'book_03', customerId: 'cust_103', artistIds: ['3'], customerName: 'Sneha Reddy', customerContact: '9876543212', eventType: 'Wedding', serviceAddress: '789, Tech Park, Koramangala, Bangalore', serviceDates: [new Date('2024-08-05')], date: new Date('2024-08-05'), service: 'Mehndi & Makeup', amount: 8000, status: 'Pending Approval', paidOut: false, eventDate: new Date('2024-08-07'), state: 'Karnataka', district: 'Bengaluru Urban', location: 'Koramangala' },
    { id: 'book_04', customerId: 'cust_101', artistIds: ['1'], customerName: 'Meera Iyer', customerContact: '9876543213', eventType: 'Engagement', serviceAddress: '321, Lakeview, Powai, Mumbai', serviceDates: [new Date('2024-08-10')], date: new Date('2024-08-10'), service: 'Engagement Makeup', amount: 4500, status: 'Confirmed', paidOut: false, eventDate: new Date('2024-08-11'), state: 'Maharashtra', district: 'Mumbai Suburban', location: 'Powai' },
    { id: 'book_05', customerId: 'cust_104', artistIds: [], customerName: 'Rohan Gupta', customerContact: '9876543214', eventType: 'Festival', serviceAddress: '654, MG Road, Pune', serviceDates: [new Date('2024-08-12')], date: new Date('2024-08-12'), service: 'Mehndi Package', amount: 1800, status: 'Needs Assignment', paidOut: false, eventDate: new Date('2024-08-13'), state: 'Maharashtra', district: 'Pune', location: 'MG Road' },
    { id: 'book_06', customerId: 'cust_105', artistIds: ['4'], customerName: 'Kavita Singh', customerContact: '9876543215', eventType: 'Wedding', serviceAddress: '987, Cyber City, Gurgaon', serviceDates: [new Date('2024-08-15')], date: new Date('2024-08-15'), service: 'Minimalist Mehndi', amount: 2200, status: 'Completed', paidOut: false, eventDate: new Date('2024-08-18'), state: 'Haryana', district: 'Gurugram', location: 'Cyber City' },
    { id: 'book_07', customerId: 'cust_106', artistIds: ['5'], customerName: 'Divya Kumar', customerContact: '9876543216', eventType: 'Wedding', serviceAddress: '111, Jubilee Hills, Hyderabad', serviceDates: [new Date('2024-07-28')], date: new Date('2024-07-28'), service: 'Bridal Makeup', amount: 9000, status: 'Disputed', paidOut: false, eventDate: new Date('2024-07-30'), state: 'Telangana', district: 'Hyderabad', location: 'Jubilee Hills' },
];

export const initialPromotions: Promotion[] = [
    { id: 'promo_1', code: 'WELCOME10', discount: 10, expiryDate: '2024-12-31', isActive: true },
    { id: 'promo_2', code: 'FESTIVE20', discount: 20, expiryDate: '2024-10-31', isActive: true },
    { id: 'promo_3', code: 'SUMMER15', discount: 15, expiryDate: '2024-06-30', isActive: false },
];
