import type { Artist } from '@/types';

export const artists: Artist[] = [
  {
    id: '1',
    name: 'Aisha Mehmood',
    profilePicture: 'https://picsum.photos/200/200?random=1',
    workImages: [
      'https://picsum.photos/600/400?random=11',
      'https://picsum.photos/600/400?random=12',
      'https://picsum.photos/600/400?random=13',
    ],
    services: ['mehndi'],
    location: 'Mumbai, India',
    charge: 2500,
    rating: 4.9,
    styleTags: ['bridal', 'arabic', 'intricate'],
  },
  {
    id: '2',
    name: 'Priya Sharma',
    profilePicture: 'https://picsum.photos/200/200?random=2',
    workImages: [
      'https://picsum.photos/600/400?random=21',
      'https://picsum.photos/600/400?random=22',
      'https://picsum.photos/600/400?random=23',
    ],
    services: ['makeup'],
    location: 'Delhi, India',
    charge: 5000,
    rating: 4.8,
    styleTags: ['glam', 'natural', 'wedding'],
  },
  {
    id: '3',
    name: 'Rani Kaur',
    profilePicture: 'https://picsum.photos/200/200?random=3',
    workImages: [
      'https://picsum.photos/600/400?random=31',
      'https://picsum.photos/600/400?random=32',
      'https://picsum.photos/600/400?random=33',
    ],
    services: ['mehndi', 'makeup'],
    location: 'Bangalore, India',
    charge: 7000,
    rating: 5.0,
    styleTags: ['luxury', 'traditional', 'modern'],
  },
  {
    id: '4',
    name: 'Sunita Patel',
    profilePicture: 'https://picsum.photos/200/200?random=4',
    workImages: [
      'https://picsum.photos/600/400?random=41',
      'https://picsum.photos/600/400?random=42',
      'https://picsum.photos/600/400?random=43',
    ],
    services: ['mehndi'],
    location: 'Ahmedabad, India',
    charge: 1800,
    rating: 4.7,
    styleTags: ['minimalist', 'floral', 'indian'],
  },
  {
    id: '5',
    name: 'Fatima Khan',
    profilePicture: 'https://picsum.photos/200/200?random=5',
    workImages: [
      'https://picsum.photos/600/400?random=51',
      'https://picsum.photos/600/400?random=52',
      'https://picsum.photos/600/400?random=53',
    ],
    services: ['makeup'],
    location: 'Hyderabad, India',
    charge: 4500,
    rating: 4.9,
    styleTags: ['dewy', 'bold', 'party'],
  },
  {
    id: '6',
    name: 'Geeta Singh',
    profilePicture: 'https://picsum.photos/200/200?random=6',
    workImages: [
      'https://picsum.photos/600/400?random=61',
      'https://picsum.photos/600/400?random=62',
      'https://picsum.photos/600/400?random=63',
    ],
    services: ['mehndi', 'makeup'],
    location: 'Pune, India',
    charge: 6500,
    rating: 4.8,
    styleTags: ['airbrush', 'arabic', 'fusion'],
  },
    {
    id: '7',
    name: 'Zara Begum',
    profilePicture: 'https://picsum.photos/200/200?random=7',
    workImages: [
      'https://picsum.photos/600/400?random=71',
      'https://picsum.photos/600/400?random=72',
      'https://picsum.photos/600/400?random=73',
    ],
    services: ['mehndi'],
    location: 'Kolkata, India',
    charge: 3000,
    rating: 4.9,
    styleTags: ['traditional', 'peacock', 'detailed'],
  },
  {
    id: '8',
    name: 'Simran Reddy',
    profilePicture: 'https://picsum.photos/200/200?random=8',
    workImages: [
      'https://picsum.photos/600/400?random=81',
      'https://picsum.photos/600/400?random=82',
      'https://picsum.photos/600/400?random=83',
    ],
    services: ['makeup'],
    location: 'Chennai, India',
    charge: 5500,
    rating: 4.7,
    styleTags: ['south indian', 'bridal', 'temple'],
  },
];
