

import type { ServicePackage } from '@/types';

export const packages: ServicePackage[] = [
  {
    id: 'pkg_bridal_01',
    name: 'Bridal Mehendi',
    service: 'mehndi',
    description: 'Covers both hands on both sides up to elbow length. Intricate and detailed designs perfect for the bride.',
    price: 5000,
    image: 'https://picsum.photos/600/400?random=301',
    tags: ['Organic Henna', 'Bridal Special'],
  },
  {
    id: 'pkg_semibridal_02',
    name: 'Semi Bridal Mehendi',
    service: 'mehndi',
    description: 'A perfect balance of tradition and elegance.',
    price: 4000,
    image: 'https://picsum.photos/600/400?random=302',
    tags: ['Organic Henna'],
  },
  {
    id: 'pkg_bridalfeet_03',
    name: 'Bridal Feet Mehendi',
    service: 'mehndi',
    description: 'Complements the bridal hand mehendi.',
    price: 2000,
    image: 'https://picsum.photos/600/400?random=303',
    tags: ['Organic Henna'],
  },
  {
    id: 'pkg_feet_04',
    name: 'Feet Mehendi',
    service: 'mehndi',
    description: 'Covers toes and mid-portion, no sides included. Simple and elegant for any occasion.',
    price: 1000,
    image: 'https://picsum.photos/600/400?random=304',
    tags: ['Organic Henna'],
  },
  {
    id: 'pkg_megabridal_05',
    name: 'Mega Bridal Feet Mehendi',
    service: 'mehndi',
    description: 'Extensive coverage for the feet, including toes, mid-portion, and all four sides with heavy designs.',
    price: 5000,
    image: 'https://picsum.photos/600/400?random=305',
    tags: ['Organic Henna', 'Full Coverage'],
  },
  {
    id: 'pkg_wrist_06',
    name: 'Wrist Length Mehendi',
    service: 'mehndi',
    description: 'Covers both hands on both sides up to the wrist. Ideal for guests and smaller functions.',
    price: 3000,
    image: 'https://picsum.photos/600/400?random=306',
    tags: ['Organic Henna'],
  },
  {
    id: 'pkg_bridal_makeup_07',
    name: 'Bridal Makeup',
    service: 'makeup',
    description: 'Complete bridal makeup including HD or airbrush techniques, hair styling, and draping.',
    price: 15000,
    image: 'https://picsum.photos/600/400?random=307',
    tags: ['HD Makeup', 'Airbrush', 'Bridal'],
  },
  {
    id: 'pkg_party_makeup_08',
    name: 'Party Makeup',
    service: 'makeup',
    description: 'Get ready for any event with our glam party makeup. Includes eyes, base, and lips.',
    price: 4500,
    image: 'https://picsum.photos/600/400?random=308',
    tags: ['Glam', 'Evening Look'],
  },
   {
    id: 'pkg_prewedding_photo_09',
    name: 'Pre-Wedding Shoot',
    service: 'photography',
    description: 'A 4-hour pre-wedding photography session at a location of your choice. Includes 50 edited photos.',
    price: 25000,
    image: 'https://picsum.photos/600/400?random=309',
    tags: ['Candid', 'Romantic', 'Outdoor'],
  },
  {
    id: 'pkg_event_photo_10',
    name: 'Event Coverage',
    service: 'photography',
    description: 'Full coverage for a 6-hour event. Ideal for weddings, engagements, or corporate events.',
    price: 40000,
    image: 'https://picsum.photos/600/400?random=310',
    tags: ['Wedding', 'Candid', 'Full Coverage'],
  },
];
